export const SEARCH_FIELD_CHANGED = "SEARCH_FIELD_CHANGED"

export const SEARCH_REQUEST_LOADING = "SEARCH_REQUEST_LOADING"
export const SEARCH_REQUEST_ERROR = "SEARCH_REQUEST_ERROR"
export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS"
